# Generated by Django 5.1 on 2024-08-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('palabras_clave', models.CharField(max_length=100)),
                ('copia', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_nac', models.DateField()),
                ('nacionalidad', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Group_Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('linea', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('1C', 'Categoría 1C')], max_length=2)),
            ],
            options={
                'verbose_name': 'Grupo de Investigación',
                'verbose_name_plural': 'Grupos de Investigación',
            },
        ),
        migrations.CreateModel(
            name='Tipo_articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Artículo',
                'verbose_name_plural': 'Tipos de Artículo',
            },
        ),
        migrations.CreateModel(
            name='Acta_congreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicion', models.IntegerField()),
                ('ciudad', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=60)),
                ('frecuencia', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=60)),
                ('ano_primer_ed', models.DateField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.articulo')),
            ],
            options={
                'verbose_name': 'Acta de Congreso',
                'verbose_name_plural': 'Actas de Congreso',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.autor'),
        ),
        migrations.AddField(
            model_name='autor',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.group_invest'),
        ),
        migrations.CreateModel(
            name='Informe_tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('centro_pub', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.articulo')),
            ],
            options={
                'verbose_name': 'Informe Técnico',
                'verbose_name_plural': 'Informes Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Revista_cientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('editor', models.CharField(max_length=60)),
                ('ano_inicio', models.DateField()),
                ('periodicidad', models.CharField(max_length=60)),
                ('tema', models.CharField(max_length=60)),
                ('num_edicion', models.IntegerField()),
                ('paginas', models.CharField(max_length=20)),
                ('ano_pub', models.IntegerField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.articulo')),
            ],
            options={
                'verbose_name': 'Revista Científica',
                'verbose_name_plural': 'Revistas Científicas',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.tipo_articulo'),
        ),
    ]
