# Generated by Django 5.1 on 2024-08-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_articulo',
            name='tipo',
            field=models.CharField(choices=[('Informe Técnico', 'Tipo Informe Técnico'), ('Acta de Congreso', 'Tipo Acta de Congreso'), ('Revista Científica', 'Tipo Revista Científica')], max_length=100),
        ),
    ]
