# Generated by Django 5.1 on 2024-08-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_tipo_articulo_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_articulo',
            options={},
        ),
        migrations.RemoveField(
            model_name='tipo_articulo',
            name='tipo',
        ),
    ]
