# Generated by Django 5.1 on 2024-08-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_tipo_articulo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_articulo',
            name='tipo',
            field=models.CharField(default='Default Value', max_length=100),
        ),
    ]
