# Generated by Django 5.1 on 2024-08-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_tipo_articulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_invest',
            name='categoria',
            field=models.CharField(choices=[('Categoría A', 'A'), ('Categoría B', 'B'), ('Categoría C', 'C'), ('Categoría D', 'D'), ('Categoría E', 'E')], max_length=12),
        ),
    ]
