# Generated by Django 5.1 on 2024-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_auto_20240908_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_articulo',
            name='tipo',
            field=models.CharField(choices=[('default_value', 'Default Value'), ('Informe Técnico', 'Informe Técnico'), ('Acta de Congreso', 'Acta de Congreso'), ('Revista Científica', 'Revista Científica')], default='default_value', max_length=100),
        ),
    ]
