# Generated by Django 5.1 on 2024-09-24 22:26

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_alter_tipo_articulo_tipo'),  # Reemplaza con la última migración antes de esta
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta_congreso',
            name='ano_primer_ed',
        ),
    ]
