# Generated by Django 5.1 on 2024-09-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_alter_tipo_articulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta_congreso',
            name='ano_primer_ed',
            field=models.IntegerField(),
        ),
    ]
